---
collections:
- name: community.aws
- name: community.general
- name: community.crypto
- name: containers.podman
- name: servicenow.itsm
- name: infra.ee_utilities
- name: kubernetes.core
- name: redhat.openshift
- name: redhat.openshift_virtualization
- name: hfenner.aap_utilities
  source: https://github.com/hfenner/aap_utilities.git
  version: devel
  type: git
