---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    output_path: /home/ec2-user/aap_resources
    filetree_controller_projects: "{{ output_path }}/Default/projects"
    filetree_controller_workflow_job_templates: "{{ output_path }}/Default/workflow_job_templates"
    controller_oauthtoken: "{{ lookup('ansible.builtin.env', 'AAP_TOKEN') }}"
    controller_hostname: aap-controller.2v2hs.sandbox2869.opentlc.com
    controller_validate_certs: false
    controller_configuration_dispatcher_roles:
    - role: workflow_job_templates
      var: controller_workflows
      tags: workflow_job_templates
  

  tasks:
  - name: Read projects
    ansible.builtin.include_role:
      name: infra.controller_configuration.filetree_read
      tasks_from: workflow_job_templates.yml

  - name: Apply projects
    ansible.builtin.include_role:
      name: infra.controller_configuration.dispatch
