---
collections:
  - community.okd
  - kubernetes.core
  - community.general
  - amazon.aws
  - vmware.vmware_rest 
  - community.vmware
  - awx.awx
  - community.crypto
  - community.aws
  - ansible.windows
  - ansible.controller
  - community.postgresql
  - infra.controller_configuration
  - name: hfenner.aap_utilities
    source: https://github.com/hfenner/aap_utilities.git
    type: git
    version: devel
